const fs = require('fs');
const path = require('path');

exports.handler = async (event, context) => {
    try {
        const rootDir = __dirname;
        
        const stylePath = path.join(rootDir, 'get-ui-assets/style.css');
        const scriptPath = path.join(rootDir, 'get-ui-assets/script.js');

        let styleContent = '';
        let scriptContent = '';

        try { styleContent = fs.readFileSync(stylePath, 'utf8'); } catch (e) { styleContent = '/* CSS not found */'; }
        try { scriptContent = fs.readFileSync(scriptPath, 'utf8'); } catch (e) { scriptContent = '// JS not found'; }

        const html = [
            '<!DOCTYPE html>',
            '<html lang="kk">',
            '<head>',
            '    <meta charset="UTF-8">',
            '    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">',
            '    <title>QazTTS</title>',
            '    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">',
            '    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">',
            '    <style>',
            styleContent,
            '    </style>',
            '</head>',
            '<body>',
            '    <div id="toast-notification" class="toast"></div>',
            '    ',
            '    <div id="screen-list">',
            '        <div class="navbar">',
            '            <div class="logo">Qaz<span>TTS</span></div>',
            '            <div class="profile-trigger" id="profileTrigger"><i class="fa-solid fa-circle-user"></i></div>',
            '        </div>',
            '        <div class="search-container"><input type="text" id="search" placeholder="Дауысты іздеу..." autocomplete="off"></div>',
            '        <div class="filters" id="filterContainer"></div>',
            '        <div id="voiceList" class="voice-list"><div style="text-align: center; color: #555; padding: 20px;">Жүктелуде...</div></div>',
            '    </div>',
            '',
            '    <div id="screen-settings" class="hidden">',
            '        <div class="settings-header">',
            '            <button id="backBtn" class="btn-back"><i class="fa-solid fa-arrow-left"></i> Артқа</button>',
            '            <div class="lang-indicator"><img src="img/kk.svg" id="setting-lang-flag"><span id="setting-lang-name">Қазақ тілі</span></div>',
            '        </div>',
            '        ',
            '        <div class="info-card">',
            '            <div class="info-header">',
            '                <div class="info-name">',
            '                    <span id="st-name"></span>',
            '                    <i class="fa-solid fa-circle-play play-icon" id="previewBtn"></i>',
            '                </div>',
            '                <img id="st-flag" src="img/kk.svg" width="28" style="border-radius: 4px;">',
            '            </div>',
            '            <div class="info-meta">',
            '                <span id="st-gender"></span> <span style="color: #444; margin: 0 8px;">•</span> ',
            '                <span id="st-lang"></span> <span style="color: #444; margin: 0 8px;">•</span> ',
            '                <span id="st-provider"></span>',
            '            </div>',
            '        </div>',
            '        ',
            '        <div id="standard-controls" class="controls-card">',
            '            <div class="slider-row">',
            '                <div class="slider-header"><span class="slider-title lng-speed">Speech Speed</span><span class="slider-value" id="rate-val">+0%</span></div>',
            '                <input type="range" min="-50" max="100" value="0" step="5" id="rate">',
            '            </div>',
            '            <div class="slider-row">',
            '                <div class="slider-header"><span class="slider-title lng-tonality">Tonality</span><span class="slider-value" id="pitch-val">+0Hz</span></div>',
            '                <input type="range" min="-50" max="50" value="0" step="1" id="pitch">',
            '            </div>',
            '        </div>',
            '',
            '        <div id="issai-controls" class="controls-card hidden">',
            '            <div style="margin-bottom: 24px;">',
            '                <span class="slider-title lng-emotion" style="margin-bottom: 12px; display:block;">Emotion</span>',
            '                <div class="select-wrapper">',
            '                    <select id="emotionSelect"></select>',
            '                    <i class="fa-solid fa-chevron-down select-icon"></i>',
            '                </div>',
            '            </div>',
            '            <div>',
            '                <span class="slider-title lng-tags" style="margin-bottom: 12px; display:block;">Tags</span>',
            '                <div class="tags-grid" id="tagsContainer">',
            '                    <div class="tag-chip" data-key="laugh" onclick="copyTag(\'[laugh]\')">laugh</div>',
            '                    <div class="tag-chip" data-key="cough" onclick="copyTag(\'[cough]\')">cough</div>',
            '                    <div class="tag-chip" data-key="sigh" onclick="copyTag(\'[sigh]\')">sigh</div>',
            '                    <div class="tag-chip" data-key="sniffle" onclick="copyTag(\'[sniffle]\')">sniffle</div>',
            '                    <div class="tag-chip" data-key="gasp" onclick="copyTag(\'[gasp]\')">gasp</div>',
            '                    <div class="tag-chip" data-key="stutter" onclick="copyTag(\'[stutter]\')">stutter</div>',
            '                    <div class="tag-chip" data-key="whisper" onclick="copyTag(\'[whisper]\')">whisper</div>',
            '                </div>',
            '            </div>',
            '        </div>',
            '',
            '        <div id="elevenlabs-controls" class="controls-card hidden">',
            '            <div class="slider-row">',
            '                <div class="slider-header"><span class="slider-title lng-stability">Stability</span><span class="slider-value" id="stability-val">0.50</span></div>',
            '                <input type="range" min="0" max="100" value="50" id="stability">',
            '            </div>',
            '            <div class="slider-row">',
            '                <div class="slider-header"><span class="slider-title lng-similarity">Similarity</span><span class="slider-value" id="similarity-val">0.75</span></div>',
            '                <input type="range" min="0" max="100" value="75" id="similarity">',
            '            </div>',
            '        </div>',
            '',
            '        <button id="submitBtn" class="main-action-btn">Дыбыстау</button>',
            '    </div>',
            '',
            '    <div id="screen-account-details" class="hidden">',
            '        <div class="settings-header"><button id="accBackBtn" class="btn-back"><i class="fa-solid fa-arrow-left"></i> Баптаулар</button></div>',
            '        <h2 id="accDetailTitle" style="margin-bottom: 20px;">API Баптау</h2>',
            '        ',
            '        <div class="info-card" style="margin-bottom: 20px;">',
            '            <p style="color: var(--text-gray); font-size: 14px; margin-bottom: 10px;"><span id="apiKeyLabelText">API Key:</span></p>',
            '            <div class="api-input-wrapper">',
            '                <input type="password" id="apiKeyInput" placeholder="Paste your API key here..." autocomplete="off">',
            '                <i class="fa-solid fa-eye-slash" id="toggleApiVisibility"></i>',
            '            </div>',
            '            <p id="apiHelpText" style="font-size: 12px; color: #888; margin-top: 10px; line-height: 1.4;"></p>',
            '            <a id="getKeyLink" href="#" target="_blank" style="display: inline-block; margin-top: 12px; color: var(--primary); font-size: 13px; text-decoration: none; font-weight: 500;"><i class="fa-solid fa-external-link" style="font-size: 11px; margin-right: 4px;"></i> <span id="getKeyText">Кілтті алу</span></a>',
            '        </div>',
            '',
            '        <div class="actions-row" style="margin-bottom: 24px;">',
            '            <button class="main-action-btn" id="saveKeyBtn">Сақтау</button>',
            '            <button class="delete-btn-outline" id="deleteKeyBtn">Өшіру</button>',
            '        </div>',
            '',
            '        <div id="balanceContainer" class="token-card hidden">',
            '            <div id="tokensLeftLabel" style="font-size: 13px; opacity: 0.8; margin-bottom: 12px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px;">Лимит:</div>',
            '            <div id="det-tokens">...</div>',
            '        </div>',
            '    </div>',
            '',
            '    <div id="profileModal" class="modal-overlay hidden">',
            '        <div class="modal-content" id="modalContent">',
            '            <div class="modal-handle"></div>',
            '            <div class="modal-header"><h3 id="modalTitle">Қызметтер</h3><button id="closeProfile" class="close-btn">&times;</button></div>',
            '            ',
            '            <div class="lang-tabs">',
            '                <button class="tab-btn active" data-lang="kk">Қаз</button>',
            '                <button class="tab-btn" data-lang="en">Eng</button>',
            '                <button class="tab-btn" data-lang="ru">Рус</button>',
            '            </div>',
            '            ',
            '            <div class="profile-menu-list">',
            '                <div class="menu-item" id="apiIssaiItem">',
            '                    <img src="img/mangisoz.ico" class="menu-icon" alt="ISSAI">',
            '                    <div class="menu-info">',
            '                        <span class="menu-label">ISSAI API</span>',
            '                        <span class="menu-sub" id="status-issai">...</span>',
            '                    </div>',
            '                    <i class="fa-solid fa-chevron-right" style="font-size:12px;color:#888;"></i>',
            '                </div>',
            '                <div class="menu-divider"></div>',
            '                <div class="menu-item" id="apiElevenItem">',
            '                    <img src="img/elevenlabs.ico" class="menu-icon" alt="ElevenLabs">',
            '                    <div class="menu-info">',
            '                        <span class="menu-label">ElevenLabs API</span>',
            '                        <span class="menu-sub" id="status-eleven">...</span>',
            '                    </div>',
            '                    <i class="fa-solid fa-chevron-right" style="font-size:12px;color:#888;"></i>',
            '                </div>',
            '            </div>',
            '        </div>',
            '    </div>',
            '',
            '    <script>',
            scriptContent,
            '    </script>',
            '</body>',
            '</html>'
        ].join('\n');

        return {
            statusCode: 200,
            headers: { "Content-Type": "text/html" },
            body: html
        };
    } catch (error) {
        return { statusCode: 500, body: "Error: " + error.message };
    }
};
